#!/bin/sh
# Generate README sections from actual file structure
# Updates command counts, indexes, and other generative content

set -e

COMMANDS_DIR="$(cd "$(dirname "$0")/.." && pwd)"
README="$COMMANDS_DIR/README.md"

# Count commands in a category
count_in_category() {
    category="$1"
    find "$COMMANDS_DIR/$category" -type f -name "*.md" ! -name "README.md" 2>/dev/null | wc -l
}

# Get total command count
total_commands() {
    find "$COMMANDS_DIR" -type d -mindepth 1 -maxdepth 1 ! -name ".*" ! -name "scripts" ! -name "templates" ! -name "settings" | \
    while read -r dir; do
        find "$dir" -type f -name "*.md" ! -name "README.md" 2>/dev/null
    done | wc -l
}

# Generate complete index line
generate_index_line() {
    category="$1"
    display_name="$2"
    count=$(count_in_category "$category")
    
    if [ "$count" -eq 0 ]; then
        return
    fi
    
    # Get command list (just the base names without .md)
    cmds=$(find "$COMMANDS_DIR/$category" -type f -name "*.md" ! -name "README.md" 2>/dev/null | \
           sort | \
           sed "s|$COMMANDS_DIR/$category/||" | \
           sed 's|\.md$||' | \
           tr '\n' ',' | sed 's/,$//' | sed 's/,/, /g')
    
    echo "**$display_name ($count):** $cmds"
}

# Generate the complete index section
TEMP_INDEX=$(mktemp)
{
    echo "# Complete Command Index (A1-Z9)"
    echo ""
    echo "All commands indexed alphabetically by category, numbered semantically within each category."
    echo ""
    generate_index_line "architect" "A - Architect"
    generate_index_line "behavior" "B - Behavior"
    generate_index_line "code-quality" "C - Code-Quality"
    generate_index_line "documentation" "D - Documentation"
    generate_index_line "eval" "E - Eval"
    generate_index_line "git" "G - Git"
    generate_index_line "internet" "I - Internet"
    generate_index_line "meta" "M - Meta"
    generate_index_line "project-management" "P - Project-Management"
    generate_index_line "research" "R - Research"
    generate_index_line "security" "S - Security"
    generate_index_line "transcript" "T - Transcript"
    generate_index_line "workflow" "W - Workflow"
    echo ""
    echo "**Total: $(total_commands) commands** - All active and available for use."
    echo ""
    echo "**Note:** Command counts and indexes are generated by code, not manually maintained. Use \`meta/M8-identify-generative-content.md\` to identify what should be automated."
} > "$TEMP_INDEX"

# Update README - replace section from "# Complete Command Index" to "---"
awk -v tempfile="$TEMP_INDEX" '
    BEGIN {
        # Read the new section
        while ((getline line < tempfile) > 0) {
            new_section = new_section line "\n"
        }
        close(tempfile)
    }
    /^# Complete Command Index \(A1-Z9\)/ {
        # Found start of section - print new content
        printf "%s", new_section
        in_section = 1
        next
    }
    /^---$/ && in_section {
        # End of section - print delimiter and stop skipping
        in_section = 0
        print
        next
    }
    in_section {
        # Skip old section content
        next
    }
    {
        # Print everything else normally
        print
    }
' "$README" > "$README.tmp" && mv "$README.tmp" "$README"

# Cleanup
rm -f "$TEMP_INDEX"

echo "✅ Generated README sections updated"